title: Creating a Release Based Workflow
tagline: Learn and practice a workflow based around creating releases on GitHub.
description: This course focuses on releases, and more complex branching strategies.
tags:
  - GitHub
template:
    name: release-based-workflow
    repo: release-workflow-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.1_welcome.md
    data:
      releases: '{{ repoURl }}/releases'
  - type: octokit
    method: projects.createRepoProject
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    name: Release 2.0
    body: This project board tracks the steps necessary for Release 2.0.
#  - type: octokit
#    method: projects.createProjectColumn
#    project_id: 1
#    name: To Do
#  - type: octokit
#    method: projects.createProjectColumn
#    project_id: 1
#    name: In progress
#  - type: octokit
#    method: projects.createProjectColumn
#    project_id: 1
#    name: Done
steps:
  #1
  - title: Create a release
    description: Create a release for the most recent commit on the master branch.
    event: release.published
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createIssue
        title: Bug found, please fix
        body: 01.1_bug-issue.md #edit to have instructions be: added to project board
        action_id: bugIssue
      - type: respond
        issue: Welcome
        with: 01.2_next-step.md
        data:
          url: '%actions.bugIssue.data.html_url%'
          releases: '{{ repoURl }}/releases'
      - type: closeIssue
        issue: Welcome

  #2
  - title: Organize the release with a project board
    description: Add a card to the "in progress" column of the project board.
    event: project_card.created
    link: '{{ repoURL }}/projects/1'
    actions:
      - type: respond
        with: 02.1_fix-bug.md
        issue: 2

  #3
  - title: Fix the bug
    description: Create a branch, fix the bug, and open a pull request.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: createReview
        body: 03.1_request-changes.md
        event: REQUEST_CHANGES

  #4
  - title: Create a release branch
    description: Create a release branch that will represent work for a specific release.
    event: create
    link: '{{ repoURL }}/pull/3'
    actions:      #store the branch name for use in step 6
      - type: respond
        with: 04.1_release-branch.md
        issue: 3

  #5
  - title: Edit a pull request
    description: Edit the pull request to introduce the bug fix into the release branch.
    event: pull_request.edited
    link: '{{ repoURL }}/pull/3'
    actions:
      - type: removeBranchProtection
      - type: createReview
        body: 05.1_merge.md
        event: APPROVE

  #6
  - title: Merge the pull request
    description: Merge the pull request to update the release branch.
    event: pull_request.closed
    link: '{{ repoURL }}/pull/3'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
        else:
          - type: octokit
            method: issues.edit
            state: open
            owner: '%payload.repository.owner.login%'
            repo: '%payload.repository.name%'
            number: '%payload.repository.pull_request.number%'
          - type: respond
            with: 06.1_early-close.md
      - type: updateBranchProtection
      - type: createPullRequest
        title: Merge the release branch into master
        body: 06.2_bot-pr.md
        head: v1.0 #for testing purposes only, should be replaced by variable in step 4
        action_id: releasePR
      - type: respond
        with: 06.3_nice-merge.md
        data:
          url: '%actions.releasePR.data.html_url%'
          project: '{{ repoURL }}/projects/1'
      - type: closeIssue
        issue: 2
        # update project board


  #7
  - title: Approve a pull request
    description: Review and approve the pull request that Learning Lab opened.
    event: pull_request_review.submitted
    link: '{{ repoURL }}/pull/5'
    actions:
      # - type: gate #make sure it was approval
      - type: mergePullRequest
      - type: octokit
        method: gitdata.deleteReference
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        ref: heads/v1.0 #this should also be taken from a variable
      - type: createIssue
        title: Creating a release
        body: 07.1_create-release.md
        action_id: nextIssue
      - type: respond
        with: 07.2_point-to-issue.md
        issue: 4
        data:
          url: '%actions.nextIssue.data.html_url%'

  #8
  - title: Create a final release & changelog
    description: Create a release with the most recent code, and craft release notes as a changelog.
    event: release.published
    link: '{{ repoURL }}/issues/6'
    actions:
      - type: respond
        with: 08.1_congratulations.md
        issue: 5
